### ISSUE TITLE
Дать возможность пользователю задавать свои параметры для FFMPEG и для энкодера medianocheH264

### ISSUE THREAD

**Issue by Devyatyi9** [Persivan/Eventurika-Honkai-Impact-Translation#14]
Например указывать путь до текстового файла с параметрами для ffmpeg и опционально второй текстовый для энкодера

**Comment by Persivan** [comment]
Считаю юзелесс. Выше, чем в оригинале нет смысла указывать. Ниже... в какой-нибудь вселенной челу потребуется уменьшить размер папки... В общем считаю фичу бесполезной.

**Comment by Devyatyi9** [comment]
Тогда нам надо будет подобрать лучший конфиг, но вобще это ведь не только для качества используется, вдруг кто-то решит прописать параметр `-hwaccels auto` или `-hwaccels opencl`/`-hwaccels cuda`
ну либо банальное `-threads auto -preset slow`

**Comment by Devyatyi9** [comment]
Ладно, закрою, оно просто место занимает
