### ISSUE TITLE
Файл сабов должен содержать _en в название.

### ISSUE THREAD

**Issue by Persivan** [Persivan/Eventurika-Honkai-Impact-Translation#2]
До N версии игры сабы лежали без кодирования в .usm файл. Просто file.mp4 + file_en.txt. Ребята просто переводили файл file_en.txt. 
Сейчас нам хотелось бы использовать переведенные файлы, поэтому все файлы сабов должны именоваться как это было до версии N.
Но это не красиво. Надо доделать прогу, чтобы сабы не требовалась переименовывать.

Сейчас для генерации одного file.usm файла надо:
file.avi
file.wav
file_en.txt
Нужно сделать:
file.avi
file.wav
file_en.txt ИЛИ file.txt

**Comment by Devyatyi9** [comment]
Также нужно добавить параметр позволяющий не использовать субтитры
upd: https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/commit/9b6f4ee7876eda05fc839459b1a29a12793f13be

**Comment by Devyatyi9** [comment]
Исправлено в https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/commit/8bad95632968ea233f8e5e693dd98976642d3d82
Пока без билда
