### ISSUE TITLE
Сборка usm файла встаёт на этапе после конвертации ffmpeg'ом

### ISSUE THREAD

**Issue by Devyatyi9** [Persivan/Eventurika-Honkai-Impact-Translation#3]
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/5b859d3a-cba0-40c5-8bb5-75ea299be428)
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/446cafe6-09fe-4260-babf-c60861af3d51)
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/57c2ac62-ce64-4583-8dff-cf0d821fa928)
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/b8d4f01b-acf5-4dbb-9251-a342b7b8b0f3)

проверено на релизной версии
```
@echo off
title .usm_build
:: Использование: USM_builder <input_directory> <ffmpeg_path> <ffprobe_path> <encoder_path> <output_directory>
"./distr/USM_Builder/USM_builder.exe" "usm_builder_input/" "D:/ProjectsD/ffmpeg/bin/ffmpeg.exe" "D:/ProjectsD/ffmpeg/bin/ffprobe.exe" "D:/ProjectsD/Scaleform VideoEncoder/4.6/" "output_directory/"
pause
```

**Comment by Devyatyi9** [comment]
В разделе "Как заменить субтитры" в пункте 13.
[ссылка на баг указаный в ридми](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/blob/main/README.md#как-заменить-субтитры)

Создаются файлы с размером 0 байт, если завершить выполнение то файлы обретают вес и форму
Папка предварительно удалялась, эффект точно такой же как если бы папка не была удалена
@Persivan такие дела

**Comment by Persivan** [comment]
@Devyatyi9 вот эта строка закрывает вывод от ffmpeg
https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/blob/d29aa7e65860eb7ce6728318c6491900d2fe8bdf/USM_Builder/USM_builder/FfmpegHelper.cs#L82
Но если ее перевести в false, то будет ошибка 
https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/blob/d29aa7e65860eb7ce6728318c6491900d2fe8bdf/USM_Builder/USM_builder/FfmpegHelper.cs#L91

Я бросил разбираться с этим, потому что не знаю какие параметры надо указывать. FFMPEG видит, что существует файл и ожидает от пользователя ввода "yes" для перезаписи файла (уверен в этом на 99%).

**Как должно работать:**
Если файл существует, то надо перезаписать его. НО! если там всегда создается файл 0 байт, а потом спрашивает перезапись, то это баг. Можно в качестве временного решения включить перезапись всегда, потом исправим.

Если не понятно описал, могу дополнить, скажи.

**Comment by Devyatyi9** [comment]
Да, я думаю можно закодить перезапись действием по-умолчанию

**Comment by Devyatyi9** [comment]
Поправил (хотя происходит фэйл из-за субтитров)

**Comment by Devyatyi9** [comment]
А какие есть идеи по автоматическому вводу yes? Как это можно сделать
Думаю наверное можно параметр -y добавить и всё

**Comment by Persivan** [comment]
> А какие есть идеи по автоматическому вводу yes? Как это можно сделать Думаю наверное можно параметр -y добавить и всё

сработало?)

**Comment by Devyatyi9** [comment]
Да
