### ISSUE TITLE
Args может быть пустая строка, что ломает программу

### ISSUE THREAD

**Issue by Persivan** [Persivan/Eventurika-Honkai-Impact-Translation#5]

**Comment by Persivan** [comment]
Например запуск программы:
USM_builder "" "" "" "" "" ""
Есть проверка на количество передаваемых параметров, но нет защиты на пустую строку

**Comment by Devyatyi9** [comment]
Вот по твоему примеру, с 6-тю параметрами
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/315188eb-32e7-43c5-95fd-4ca454e87684)
И с пятью тоже самое
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/c49d46c4-7287-48d7-a3de-d3c7f990afa8)

**Comment by Devyatyi9** [comment]
@Persivan проверяй https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/commit/180c64fb015c72b36a1e7fd0b8108106c13b2efc

**Comment by Devyatyi9** [comment]
На всякий случай посмотрел как это в прошлом последнем билде выглядело
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/bafe4a84-1b92-4190-ba14-9b8ccd1dd793)
В актуальной пишет так как предполагается
![image](https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/assets/5161472/221214ff-374d-4dbe-8473-a29c99cea5c6)

**Comment by Persivan** [comment]
Топ)
