### ISSUE TITLE
Некорректный fps при сборке usm файла (ffmpeg не передаёт в аутпут)

### ISSUE THREAD

**Issue by Devyatyi9** [Persivan/Eventurika-Honkai-Impact-Translation#8]
функция `RunFFmpegCommand()` в FfmpegHelper.cs
На выходе получался файл с 10 фпс

**Comment by Devyatyi9** [comment]
https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/blob/34df06fabfbfc470c3cc4bb0e82eb1f803afbcc0/USM_Builder/USM_builder/Builder.cs#L151
```float frameRate = ffmpegHelper.GetVideoFrameRate($"{IOStore.tempFolder}/{file.filename}.avi"); // появляется красный текст: At least one output file must be specified```

**Comment by Persivan** [comment]
RunFFmpegCommand() всегда возвращает "aboba" (хардкод), нужно разобраться, как запускать процессы, направляя поток в консоль и переменную одновременно.

**Comment by Devyatyi9** [comment]
Исправлено в https://github.com/Persivan/Eventurika-Honkai-Impact-Translation/commit/e34c61341f21ad442d9210d605b6cd9688c21c82
